use strict;
use warnings;
my @strs = qw/ABGGEGBCFEBFBAF FFGFACCCECDGCDGAFFFACGDA EEDCAEAFBDDEEDGGA GDCAGFFAACBGEDBAFBCDECGAE EDB GADGADEDBCGABDDCBBDBEAD GADBB DFCE BFGCGCBEDC EDGADBGGDDFEEGGFDGCAFBFGFAAD DDAEBGACDFDGDAB EEDCECFFAE ADDBEEABFEAB FEEBFDGAADAE GB/;
@strs = sort @strs;
print ($strs[6] . "\n");
